version: "3"

services:
  backend:
    image: "myimage:${BUILD_NUMBER}"
    build:
      context: ./
    volumes:
      - ./:/meetup/
    ports:
      - 8090:8090
    command: python meetup/manage.py runserver 0:8090
